# Makefile for OBCViewer
# Developed for Linux can be ran by just make

# CPP file & object files 
OBCViewer: OBCViewer.o 
	g++ -o OBCViewer OBCViewer.cpp

# Start OBCViewer with make command
start:
	./OBCViewer
	
# Delete all Objects files
clean: 
	rm *.o
