#define _InitHalfFill
#define _Move80
#define _MoveC0
#define _Move40
#define _MoveDOUBLEY
#define _GetSector
#define _GRfillZoneVESA
#define _GRpictMoveVESA
#define _GRplotVESA
#define _GRinvertRectVESA
#define _GRinvertColorRect
