name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install g++
      run: choco install mingw -y

    - name: Compile C++20
      run: |
        g++ -std=c++20 ${{ github.workspace }}/rewritten-modern-software/LoaderMDO/LoaderMDO/LoaderMDO.cpp -o LoaderMDO.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-binary
        path: LoaderMDO.exe
