name: Build and Release (Linux)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install required libs
        run: |
          sudo apt update
          sudo apt install -y g++ make build-essential cmake libarchive-dev python3 genisoimage

      - name: Run configure
        run: ./configure

      - name: Compile all C++ programs
        run: make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-linux
          path: |
            binaries/LoaderMDO/LoaderMDO
            binaries/BCD1Creator/BCD1Creator
            binaries/DEV7Launcher/DEV7Launcher
            binaries/ModelPathDumper/ModelPathDumper
            binaries/OBJDumper/OBJDumper
            binaries/OBCViewer/OBCViewer
            binaries/CTRKViewer/CTRKViewer
            binaries/PLAViewer/PLAViewer
