name: Compile LoaderMDO x86 Original

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install g++
      run: |
        choco install mingw --params "/threads:posix" -y
        refreshenv

    - name: Set g++ path
      run: |
        echo "::set-env name=PATH::C:\tools\mingw\bin;${PATH}"

    - name: Check g++ version
      run: g++ --version

    - name: Compile LoaderMDO in Release mode
      run: |
        g++ -o LoaderMDO.exe rewritten-original-software/LoaderMDO/LoaderMDO.cpp -m32 -O2 -std=c++98 -static-libgcc -static-libstdc++ -mwindows

    - name: Archive Release artifact
      uses: actions/upload-artifact@v2
      with:
        name: LoaderMDO-release-original
        path: LoaderMDO.exe
