name: LoaderMDO Original x86

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64

      - name: Check MinGW-w64 installation
        run: |
          i686-w64-mingw32-g++ --version
          x86_64-w64-mingw32-g++ --version

      - name: Compile LoaderMDO for Windows XP
        run: |
          i686-w64-mingw32-g++ -o LoaderMDO.exe rewritten-original-software/LoaderMDO/LoaderMDO.cpp -mwindows -m32 -static-libgcc -static-libstdc++ -std=c++98 -O2

      - name: Upload Release artifact
        uses: actions/upload-artifact@v2
        with:
          name: LoaderMDO-release-windows-xp
          path: LoaderMDO.exe
