name: Build and Release (macOS)

on:
  push:
      branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Brew deps
        run: |
          brew bundle install
      
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Run configure
        run: ./configure

      - name: Compile all C++ programs
        run: make cmake

      - name: Compile all Python tools
        run: | 
          pyinstaller --onefile --distpath . tools/IMGConverter/IMGConverter.py
          pyinstaller --onefile --distpath . tools/AdultCornerDecoder/decoder.py
          pyinstaller --onefile --distpath . tools/AdultCornerEncoder/encoder.py
          pyinstaller --onefile --distpath . tools/IMGIdentifier/IMGIdentifier.py
          pyinstaller --onefile --distpath . tools/OBCEditor/OBCEditor.py
          pyinstaller --onefile --distpath . analysis-tools/PetiteDetector/PetiteDetector.py
          pyinstaller --onefile --distpath . analysis-tools/PKLiteDetector/PKLiteDetector.py
          pyinstaller --onefile --distpath . analysis-tools/SecuROMDetector/SecuROMDetector.py
          pyinstaller --onefile --distpath . tools/copyDatas/copyDatas.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-macos
          path: |
            binaries/LoaderMDO
            binaries/BCD1Creator
            binaries/DEV7Launcher
            binaries/ModelPathDumper
            binaries/OBJDumper
            binaries/OBCViewer
            binaries/CTRKViewer
            binaries/PLAViewer
            IMGConverter
            AdultCornerDecoder
            AdultCornerEncoder
            IMGIdentifier
            OBCEditor
            PetiteDetector
            PKLiteDetector
            SecuROMDetector
            copyDatas
