name: Windows (MSVC 6.0)

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Visual C++ 6.0
      run: |
        git clone --depth 1 https://github.com/itsmattkc/MSVC600
        cd MSVC600
        # Any additional setup steps for MSVC600
        # Assuming this repository provides a working environment
        # Otherwise you might need to install MSVC 6.0 locally and configure it

    - name: Setup MSVC 6.0 Environment
      shell: cmd
      run: |
        call MSVC600/VC98/Bin/vcvars32.bat

    - name: Build SYSTEM Project
      shell: cmd
      run: |
        msdev rewritten-original-software/SYSTEM/SYSTEM.dsw /MAKE "SYSTEM - Win32 Release"

    - name: Build LoaderMDO Project
      shell: cmd
      run: |
        msdev rewritten-original-software/LoaderMDO/LoaderMDO.dsw /MAKE "LoaderMDO - Win32 Release"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: compiled-windows600
        path: |
          rewritten-original-software/SYSTEM/Release/SYSTEM.exe
          rewritten-original-software/LoaderMDO/Release/LoaderMDO.exe
